<?php

namespace Dusk\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnquiryCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnquiryCategoryRepository extends EntityRepository
{
}
